### ISSUE TITLE
create sell tickets page

### ISSUE THREAD

**Issue by brentnunogawa** [manoa-tckts/manoa-tckts#11]

**Comment by dumlaoj** [comment]
- Make sure that this page can be reached from home menu button
- Make sure that this page leads to "your tickets" after being created 
- This page must the proper sell tickets functionality

**Comment by brandon-chun** [comment]
- sell tickets page can be reached from the menu bar
- the page does not have any functionality yet

for next milestone:
- working on getting the sell ticket form to work
- working on getting the search people buying tickets search bar to work
- working on getting the list of people buying tickets up on the page
