### ISSUE TITLE
create user chat page

### ISSUE THREAD

**Issue by brentnunogawa** [manoa-tckts/manoa-tckts#13]

**Comment by dumlaoj** [comment]
- Create a chat box for user
- Include a button to open the chat box
- Make chat box open when button is clicked

**Comment by brandon-chun** [comment]
Discussed with group members about the chat box, might be too hard to implement.
Will think of another feature to add onto a page for M2

**Comment by dumlaoj** [comment]
This issue has been changed from "create user chat page" to "create user notifications"
Create a feature such that when a user is interested in a ticket, they can click a button to notify the owner of the ticket. This will appear on the owner's notifications
